env:
  browser: true
  commonjs: true
  es6: true
  node: true
extends:
  - eslint:recommended
  - plugin:node/recommended

parserOptions:
  ecmaVersion: 9
  sourceType: "module"

rules:
  indent:
    - error
    - 2
    - SwitchCase: 1
  semi:
    - error
    - always
  keyword-spacing:
    - error
    - after: true
  space-before-blocks:
    - error
    - always
  space-before-function-paren:
    - error
    - asyncArrow: always
      anonymous: never
      named: never
  no-unused-vars:
    - error
    - argsIgnorePattern: "re[q|s]"
  brace-style: error
  node/shebang: 0

  quotes:
    - error
    - single
  quote-props:
    - error
    - as-needed
  node/no-unpublished-require: 0
  node/no-unsupported-features/es-syntax:
    - error
    - version: ">=8.3.0"

